# from git 2.1
version: 2
workflows:
  version: 2
  test-env-vars:
    jobs:
      - build:
          context: myvars # has an env var called MY_ENV_VAR
jobs:
  build:
    docker:
      # specify the version here
      - image: jmrizkallah/epitech_par17:api
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "8e:2d:79:55:8c:3e:50:f4:51:5b:36:67:62:d7:0b:eb"
      - checkout
      - run:
            name: Fingerprint & SSH KEY
            command: |
              #chmod 755 .circleci/deploy.sh
              ssh-keyscan $AZURE_VM_IP >> ~/.ssh/Known_hosts
            #ssh  $AZURE_VM_USER@$AZURE_VM_IP << EOF  
      - run:
            name: Copy & Run docker-compose
            command: |
              scp -r -oStrictHostKeyChecking=no ./* $AZURE_VM_USER@$AZURE_VM_IP:/home/myapp/    
      - run: 
            name: Execute Deploy.sh
            command: |
                ssh -i $AZURE_VM_SSH_FINGERPRINT $AZURE_VM_USER@$AZURE_VM_IP  \ cd /home/myapp/ \;\ chmod +x deploy.sh \;\ sh deploy.sh 
    working_directory: ~/repo
    deploy:
      machine:
        enabled: true
      steps:
      - run:
          name: Deploy Over SSH
          command:   
