
version: '3'
services:
  nodejs-server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3080:3080"
    container_name: backend
    volumes:
       - ./backend:/usr/src/app/backend
       - /usr/src/app/backend/node_modules
  vue-ui:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: vue-ui
    volumes:
       - ./client:/usr/src/app/client
       - /usr/src/app/client/node_modules
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
